vich_uploader:
    db_driver: orm

    mappings:
        fruit_image:
            uri_prefix: /images/fruits
            upload_destination: '%kernel.project_dir%/public/images/fruits'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            delete_on_remove: true