vich_uploader:
    db_driver: orm

    mappings:
        fruit_image:
            uri_prefix: /images/fruits
            upload_destination: '%kernel.project_dir%/assets/images/fruits'
            namer: Vich\UploaderBundle\Naming\OrignameNamer